    <div class="portlet" id="expert-port">
      <div class="portlet-header">Debugging Info</div>     
      <div id="debug" class="portlet-content" >
        <div id="debuglinks"></div>
        <div id="debuginfo"></div>

        <div class="collapsible-title" revealed="false">Debugging log:</div> 
        <div class="collabsible"  id="debuglog"></div>

        <div class="collapsible-title" revealed="false">Benchmarks for this session:</div> 
        <div class="collabsible" id="debugbench" ></div>
      </div> 
    </div>

