<footer id="fnal-boilerplate">
    <a href="http://www.energy.gov/"><img src="https://www.fnal.gov/pub/test/fnalincludes/v6_0/images/doe.svg" alt="Office of Science / U.S. Department of Energy" id="logo-doe"></a>
    <a href="http://www.fra-hq.org/"><img src="https://www.fnal.gov/pub/test/fnalincludes/v6_0/images/FRA_logo11.07.svg" alt="Managed by Fermi Research Alliance, LLC" id="logo-fra"></a>
    <ul class="footer-text list-unstyled">
        <li class="first">Fermi National Accelerator Laboratory</li>
        <li>Managed by <a href="http://www.fra-hq.org/">Fermi Research Alliance, LLC</a></li>
        <li class="last">for the <a href="http://www.energy.gov/">U.S. Department of Energy Office of Science</a></li>
      </ul><!-- /.footer-text -->
      <ul>
                        <li class="first"><a href="https://www.fnal.gov/pub/disclaim.html">Security, Privacy, Legal</a></li>
                        <li class="last"><a href="https://www.fnal.gov/pub/disclaim.html#cookies">Use of Cookies</a></li>
                </ul>

</footer>




