    <div class="portlet" id="gate-info-port">
      <div class="portlet-header">Event Info</div>
      <div id="gate-info" class="event-info portlet-content">
        <table border="0" class="event-info" >
          <tr>  <td width="100px" class="event-info-caption">SW Ver</td>          <td class="event-info-reco-version"></td></tr>
          <!-- <tr>  <td width="100px" class="event-info-caption">Converter</td>          <td class="event-info-converter"></td></tr>
           <tr>  <td width="100px" class="event-info-caption">File</td>          <td class="event-info-file">   </td></tr> -->
           <tr>  <td width="100px" class="event-info-caption">Run</td>            <td class="event-info-run">         </td></tr>
          <tr>  <td width="100px" class="event-info-caption">Subrun</td>         <td class="event-info-subrun">      </td></tr>
          <tr>  <td width="100px" class="event-info-caption">Gate</td>           <td class="event-info-gate">        </td></tr>
          <tr>  <td width="100px" class="event-info-caption">Time</td>       <td>
                  <span class="event-info-local-time"></span> 
                  <span class="event-info-local-date"></span> 
                  <span class="event-info-local-tz"></span>
                  (<span class="event-info-age"></span> ago)</td></tr>
          <tr>  <td width="100px" class="event-info-caption">ID Hits</td>           <td class="event-info-id-hits">          </td></tr>
          <tr>  <td width="100px" class="event-info-caption">OD Hits</td>           <td class="event-info-od-hits">          </td></tr>
          <tr>  <td width="100px" class="event-info-caption">Slices</td>            <td class="event-info-slices">           </td></tr>
          <tr>  <td width="100px" class="event-info-caption">Clusters</td>     <td class="event-info-num-clusters">     </td></tr>
          <tr>  <td width="100px" class="event-info-caption">Tracks</td>       <td class="event-info-num-track">        </td></tr>
        </table>
        <table border="0" class="event-info" >
          <tr>  <td width="100px" class="event-info-caption">ID Hits per module</td><td class="event-info-id-hits-per-mod">  </td></tr>
          <tr>  <td width="100px" class="event-info-caption">OD Hits per module</td><td class="event-info-od-hits-per-mod">  </td></tr>
          <tr>  <td width="100px" class="event-info-caption">Total PE</td>          <td class="event-info-total-pe">         </td></tr>
          <tr>  <td width="100px" class="event-info-caption">Detector</td>       <td class="event-info-detector">    </td></tr>
          <tr>  <td width="100px" class="event-info-caption">Detector Config</td><td class="event-info-det-config">  </td></tr>
          <tr>  <td width="100px" class="event-info-caption">Trigger type</td>   <td class="event-info-trigger-type"></td></tr>
          <tr>  <td width="100px" class="event-info-caption">Cal. Settings</td>  <td class="event-info-cal-settings"></td></tr>
          <tr>  <td width="100px" class="event-info-caption">GL Gate</td>        <td class="event-info-gl-gate">     </td></tr>
          <tr>  <td width="100px" class="event-info-caption">Readout</td>        <td class="event-info-readout">     </td></tr>
          <tr>  <td width="100px" class="event-info-caption">Errors</td>         <td class="event-info-errors">      </td></tr>
        </table>
      </div> <!-- gate-info -->
    </div>

