<div id="elecview-port-help-text" class="help-text dialog" title="Electronics View Port Help">
  Example help text.
</div>

<div id="time-hist-port-help-text" class="help-text dialog" title="Time Histogram Port Help">
	The selected slice will be highlighted on the histogram.  You can change the time scale by clicking and dragging below the axis and shift the histogram by clicking and dragging above the axis.  Only hits that are shown on the time histogram will be displayed.  Click the reset button in the bottom right of the window to return to the standard scale and range.  Try play sound to "hear" the event!
</div>

<div id="ph-hist-port-help-text" class="help-text dialog" title="PE Histogram Port Help">
	You can change the energy scale by clicking and dragging below the axis and shift the histogram by clicking and dragging above the axis.  Shifting to the left will remove hits of lower energy from the display and shifting to the right will include lower energy hits.  Click the reset button in the bottom right of the window to return to the standard scale and range.  
</div>

<div id="hit-map-port-help-text" class="help-text dialog" title="Hit Maps Port Help">
	Here are three views of the detector from three angles.  Move your cursor over the diagram to zoom in.  Click on a track to highlight it in al the detector views and see information about that track.  You may chose to see track info in SI units or MeV. 
</div>

<div id="tridview-port-help-text" class="help-text dialog" title="3D Port Help">
	This is a three dimensional view of the detector showing the tracks in the selected slice.  The blue hexagons represent the front and back of the detector (the black shape represents the MINOS near detector which lies behind MINERvA).  You can rotate the view by clicking while moving the mouse.  Use the controls below to zoom and move the view in the window.  The auto rotate control will slowly rotate the view automatically.  
</div>
