    <div class="portlet" id="mri-view-port">
      <div class="portlet-header">MRI View</div>
      <div class="portlet-content" >
        <!-- <div id="mri-view" class="pad" style="width:100%; height:400px"> </div> -->
        <div id="mri-view" class="pad" style="width:100%;"> </div>

        <span class="align-right" style="width: 35px;">
          <input type="checkbox" class="align-right mri-autoscan" id="mri-autoscan1" /><label for="mri-autoscan1">AutoScan</label>
        </span>
        <div style="margin-right: 40px">
        <div id="mri-slider-ends" style="margin: 5px;"></div>     
        <div id="mri-slider-grip" style="margin: 5px;"></div>        
        </div>

      </div>
    </div>
