    <div class="portlet" id="slice-info-port">
        <div class="portlet-header">Slice Info</div>
        <div id="slice-info" class="event-info portlet-content">
          <table border="0" class="event-info" >
            <tr>  <td width="100px" class="slice-color event-info-caption">Slice</td><td> <span class="slice-color event-info-slice"></span> of <span class="event-info-nslices"></span></td></tr>
            <tr>  <td width="100px" class="event-info-caption">Event ID</td>         <td>
                  <span class="event-info-det"></span>|<span class="event-info-run"></span>|<span class="event-info-subrun"></span>|<span class="event-info-gate"></span></span>
                    </td></tr>
            <tr>  <td class="event-info-caption">Time</td>       <td>
                     <span class="event-info-local-date"></span><br/>
                     (<span class="event-info-age"></span> ago)</td></tr>
               </td></tr>
                  
            <tr>  <td width="100px" class="event-info-caption">Hits</td>             <td class="event-info-idhits"></td</tr>
            <tr>  <td width="100px" class="event-info-caption">Mean time</td>        <td class="event-info-tmean" ></td></tr>
            <tr>  <td width="100px" class="event-info-caption">Total PE</td>         <td class="event-info-calpe" ></td></tr>
            <tr>  <td width="100px" class="event-info-caption">Visible Energy</td>   <td class="event-info-mev" ></td></tr>
          </table>
         </div> <!-- slice-info -->
      </div>

