<div id='slice-navigation' class="ui-state-default ui-corner-all"> 
  <div style="float:left; display: table; width: 35%;">
    <div style="display:table-cell; vertical-align: middle;  text-align:center;"></div>
    Current slice:<span id="current-slice" class="slice-color">All Hits</span><br/>
    <input type="checkbox" id="ctl-slices-auto"   name="ctl-slices-auto"  /><label for="ctl-slices-auto"  >Auto Advance Slices</label>
    </div>      
    
  <div style="margin-left: 35%;">
    <table border='0' cellpadding="1px" cellspacing="0">
      <tr>
        <td><button style="width:100%" class="ui-state-default ui-corner-all do-prev-slice-and-gate">Prev Slice &amp; Gate &nbsp;&nbsp;<span class="keypress-hint">&lt;</span></button></td>
        <td><button style="width:100%" class="ui-state-default ui-corner-all do-next-slice-and-gate">Next Slice &amp; Gate &nbsp;&nbsp;<span class="keypress-hint">&gt;</span></button></td>
      <tr/>
      <tr>
        <td><button style="width:100%" class="ui-state-default ui-corner-all do-slice-prev">Prev Slice <span class="keypress-hint">-</span></button></td>
        <td><button style="width:100%" class="ui-state-default ui-corner-all do-slice-next">Next Slice <span class="keypress-hint">+</span></button></td>
        <td><button style="width:100%" class="ui-state-default ui-corner-all do-slice-zero">Orphans <span class="keypress-hint">o</span></button></td>
        <td><button style="width:100%" class="ui-state-default ui-corner-all do-slice-all ">All hits <span class="keypress-hint">a</span></button></td>
      <tr/>
      <tr>
        <td><button style="width:100%" class="ui-state-default ui-corner-all do-prev-gate">Prev Gate <span class="keypress-hint">p</span></button></td>
        <td><button style="width:100%" class="ui-state-default ui-corner-all do-next-gate">Next Gate <span class="keypress-hint">n</span></button></td>
      </tr>
      </table>
  </div>
</div>
