<div class="portlet" id="usertrack-port">
    <div class="portlet-header"><span class="title">User Track<span></div>
    <div id="usertrack-content" class="portlet-content">
      <div id="usertrack-info">
      </div>
      <input type="checkbox" id="ctl-show-usertrack" />Show
      <button id="ctl-usertrack-snap-to-vertex">Snap to primary vertex</button>
    </div> <!-- beam-info -->
      
  </div>
