<div class="portlet" id="vetoview-port">
    <div class="portlet-header">Veto Wall</div>
  
    <div class="portlet-content">      
      <span style="display:inline-block; width:49%; ">
	  Wall 1 (Downstream)<br/>
      <div id="vetoview1" class="pad vetoview" settings="wall:1"></div> 
      </span>
      
      <span style="display:inline-block; width:49%; ">
      Wall 2 (Upstream)<br/>
      <div id="vetoview2" class="pad vetoview" settings="wall:2"></div> 
      </span>
    </div> <!-- content -->
    
    
</div> <!-- veto-view-port portlet -->

