<script type="text/javascript">
$(function(){ // do this script on page load.
  
  $('#topright_menu_'+gPageName+' a').attr('disabled','true').addClass('menu_current');
  // console.log("=============menu!",gPageName,$('#topright_menu_'+gPageName+' a'));
  
});
</script>

<ul class="menu">

<li id="topright_menu_standard" class="menu"> <a class="menu" href="arachne.html">Arachne</a></li>

<li id="topright_menu_simple"  class="menu"><a class="menu" href="simple.html">Simple </a></li>

<!-- <li id="topright_menu_live"    class="menu"><a class="menu" href="live.html">Live</a></li> -->

<li id="topright_menu_aboutsimple"   class="menu"><a class="menu" href="arachnesimplelaunchpage.html">About Simple</a></li>

<!-- <li id="topright_menu_aboutarachne"   class="menu"><a class="menu" href="arachnelaunchpage.html">About Live</a></li> -->

<li id="topright_menu_aboutminerva"  class="menu"><a class="menu" href="http://minerva.fnal.gov/">MINER&nu;A</a></li>	

</ul>
